/**
 * Walmart Kiosk Experience
 * Describes all possible paramaeters used to perform an item query.
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from './models';

export interface ItemQuery {
	/**
	 * The category id to restrict the query with
	 */
	category_id: string;

	/**
	 * The store id to perform the query on
	 */
	store_id: number;

	/**
	 * An array of facets to query with
	 */
	facets?: any;

	/**
	 * The text search query
	 */
	query?: string;

	/**
	 * The result type to return
	 */

	result_type?: string;

	/**
	 * The sorting logic to apply
	 */
	sorts?: any;

	/**
	 * The number of rows to return
	 */
	rows?: number;

	/**
	 * The row offset for pagination
	 */
	start?: number;

	/**
	 * The level of detail to request from Polaris
	 */
	response_group?: string;

	/**
	 * The additional product attributes to pull from the IRO response
	 */
	attributes?: Array<string>;

}
